#! /bin/sh

# This script initiates a shutdown when the power button has been
# pressed. It is loosely based on the sample that ships with the acpid package 
# and includes additional logging.
#
# Copyright (c) 2014 Joyent Inc., All rights reserved.
#
# This works with the Joyent Debian, Ubuntu, CentOS and Fedora images

if [ ! -f /proc/acpi/event ] ; then 
	logger -t acpid "Acpi-support not handling power button, acpid handler does not exist at /proc/acpi/event"
	exit 0
fi

# Normal handling with Joyent API logging
logger -t acpid "Joyent API shutdown called - simulating power button pressed"
/sbin/shutdown -h -P now "Joyent API shutdown called - simulating power button pressed"
