#! /bin/bash
#
# Copyright (c) 2012 Joyent Inc., All rights reserved.
#

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

# set system host name in this order
# 1) use /etc/hostname if it is not empty
# 2) use Mdata hostname if set
# 3) use what is sent from DHCP client to set hostname

# if /etc/hostname is set then we always use that first
if [ -f /etc/hostname -a -s /etc/hostname ]; then
   out=$(grep "^[[:alnum:]].*$" /etc/hostname | wc -l)
   if [ $out -eq 1 ]; then
      out=$(cat /etc/hostname)
      lib_smartdc_info "Using /etc/hostname to set system hostname to $out"
      hostname "$out"
      exit 0
   else
      lib_smartdc_info "/etc/hostname does not have a valid hostname"
   fi 
fi

mdata_hostname=$($MDATA_GET_BIN "hostname" 2>>/dev/console)

if [ $? -eq 0 -a ! -z "$mdata_hostname" ]; then  
   lib_smartdc_info "Metadata hostname set to $mdata_hostname"
   lib_smartdc_info "Setting hostname to $mdata_hostname"
   hostname "$mdata_hostname"
else
   if [ -z $1 ]; then
      lib_smartdc_info "DHCP client did not get hostname from server"
   else
      lib_smartdc_info "DHCP client got hostname ( $1 ) from server"
      lib_smartdc_info "Setting hostname to $1"
      hostname "$1"
   fi
fi

exit 0
