#! /bin/bash

# Copyright 2014, Joyent Inc. All rights reserved
# Set VM UUID in /etc/hostname. This is run at firstboot only.

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

lib_smartdc_info "Start of $(basename $0) script"

# ** This script must be run once at provision via firstboot **
UUID=$(mdata-get sdc:uuid)
echo $UUID > /etc/hostname

lib_smartdc_info "/etc/hostname created with $UUID"