#!/bin/bash
#
# Copyright (c) 2012 Joyent Inc., All rights reserved.
#

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

# set overwrite_root_akeys to the string OVERWRITE 
# to overwrite root authorized_keys on reboot
overwrite_authorized_flag=$($MDATA_GET_BIN overwrite_root_akeys 2>>/dev/console)


if [ "$overwrite_authorized_flag" = "OVERWRITE" -o "$overwrite_authorized_flag" = "overwrite" -o "$overwrite_authorized_flag" = "Overwrite" ]; then  
   lib_smartdc_info "Metadata fiels overwrite_root_akeys set to - $overwrite_authorized_flag - Overwriting /root/.ssh/authorized_keys"
   lib_smartdc_info "Removine /root/.ssh/authorized_keys"
   rm -f /root/.ssh/authorized_keys
fi

if [[ ! -f /root/.ssh/authorized_keys ]]; then
    authorized_keys=$($MDATA_GET_BIN root_authorized_keys | sed 's/\(ssh-rsa\ \)/\n\1/g' | sed 's/\(ssh-dss\ \)/\n\1/g' 2>>/dev/console)
    if [[ -n ${authorized_keys} ]]; then
        mkdir -p /root/.ssh
        echo -e "${authorized_keys}" > /root/.ssh/authorized_keys
        lib_smartdc_info "Creating /root/.ssh/authorized_keys with Metadata field root_authorized_keys"
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/authorized_keys
    fi
fi

exit 0
