#!/usr/bin/env bash
#
# Copyright (c) 2015, Joyent, Inc. All rights reserved.
#
# Debian/Ubuntu specific setup

# load common functions and vars
. /lib/smartdc/common.lib

# Add ssh host keys if they are missing.
# XXX This probably needs to just happen at first boot.
keycount=$(find /etc/ssh -name 'ssh_host_*_key*' | wc -l)
if [[ $keycount -eq 0 ]] ; then
  smartdc_info "ssh_host keys missing. Regenerating..."
  ssh-keygen -A
fi

exit 0
