#!/usr/bin/env bash
#
# Copyright 2020 Joyent, Inc.
#
# Configure resolv.conf  if not set

set -eu -o pipefail

if [[ ! -e /etc/resolv.conf ]]; then
  RESOLV=$(mktemp)

  echo "# AUTOMATIC ZONE CONFIG" > "$RESOLV"
  for i in $(mdata-get sdc:resolvers | jq -r .[]); do
    echo "nameserver $i" >> "$RESOLV"
  done
  
  chmod 644 "$RESOLV"

  mv "$RESOLV" /etc/resolv.conf 
fi
