#!/usr/bin/env bash
#
# Copyright (c) 2015, Joyent, Inc. All rights reserved.
#
# Execute metadata scripts operator-script and user-script

# load common functions and vars
. ./lib/smartdc/common.lib

# If we got as far as running the user-script the 'provision' was a success
# from here out a failure will leave the zone running.
if [[ -f /var/svc/provisioning ]]; then
  smartdc_info "Marking provision as successful: /var/svc/provision_success"
  mv /var/svc/provision{ing,_success}
fi

if [[ -x /var/svc/mdata-operator-script ]]; then
  smartdc_info "Executing metadata operator-script"
  /var/svc/mdata-operator-script
  operator_script_exit=$?
  if [[ ${operator_script_exit} -gt 0 ]]; then
    smartdc_info "WARNING: operator-script failed: exited \
      ${operator_script_exit}" >&2
  fi
fi


user_script_exit=0
if [[ -x /var/svc/mdata-user-script ]]; then
  smartdc_info "Executing metadata user-script"
  /var/svc/mdata-user-script
  [[ $? -gt 0 ]] && user_script_exit=95
fi

exit ${user_script_exit}
