#!/usr/bin/env bash
#
# Copyright 2020 Joyent, Inc.
#
# Void specific setup
#

#  Configure resolv.conf  if not set
/lib/smartdc/generate-resolv

# void attempts to write to `/proc/sys/kernel/hostname` which is currently
# unsupported in LX zones.  Until that is supported, this logic will work to
# set the hostname at boot.
if [[ -f /etc/hostname ]]; then
  hostname "$(cat /etc/hostname)"
fi
# load common functions and vars
. /lib/smartdc/common.lib
