#!/usr/bin/env bash
#
# Copyright 2020 Joyent, Inc.
#
# Void specific setup
#
#  Configure resolv.conf  if not set
if [[ ! -e /etc/resolv.conf ]]; then
  echo "# AUTOMATIC ZONE CONFIG" > /etc/resolv.conf
  for i in $(mdata-get sdc:resolvers | jq -r .[]); do
    echo "nameserver $i" >> /etc/resolv.conf
  done
fi
# void attempts to write to `/proc/sys/kernel/hostname` which is currently
# unsupported in LX zones.  Until that is supported, this logic will work to
# set the hostname at boot.
if [[ -f /etc/hostname ]]; then
  hostname "$(cat /etc/hostname)"
fi
# load common functions and vars
. /lib/smartdc/common.lib
